version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'


[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = "p:gray"
    background = "transparent"
    template = '{{ .FormattedMs }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    template = '{{ .Path }} '
    foreground = 'p:cyan'

    [blocks.segments.properties]
      style = 'folder'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    template = '<p:white>on</> {{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }} '
    foreground = 'p:red'

    [blocks.segments.properties]
      branch_icon = ' '

  [[blocks.segments]]
    type = 'project'
    style = 'plain'
    template = '{{if .Version}}<p:white>is</>  {{.Version}} {{end}}'
    foreground = 'p:cyan'

  [[blocks.segments]]
    type = 'node'
    style = 'plain'
    template = '<p:white>via</>  {{ .Full }} '
    foreground = '#p:green'

    [blocks.segments.properties]
      fetch_version = true

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = "p:gray"
    background = "transparent"
    template = '{{ .FormattedMs }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    foreground_templates = [
      "{{if gt .Code 0}}p:red{{end}}",
      "{{if eq .Code 0}}p:green{{end}}",
    ]
    type = 'text'
    style = 'plain'
    template = '❯'

[transient_prompt]
    foreground_templates = [
      "{{if gt .Code 0}}p:red{{end}}",
      "{{if eq .Code 0}}p:green{{end}}",
    ]
    background = "transparent"
    forground = "p:gray"
    template = '❯ '

[secondary_prompt]
  foreground = 'p:green'
  background = 'transparent'
  template = '❯❯ '

[palette]
black = '#000000'
cyan = '#15C2CB'
green = "#44FFD2"
white = "#F3EFF5"
gray = "#545166"
red = "#FE4A49"
